### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by kouzhudong** [zodiacon/NetworkExplorer#1]
![image](https://user-images.githubusercontent.com/18212165/102071154-0d2d5780-3e3b-11eb-9e13-b7e83667144a.png)

**Comment by kouzhudong** [comment]
![image](https://user-images.githubusercontent.com/18212165/102071215-20402780-3e3b-11eb-98c9-26448d9dab7c.png)

**Comment by zodiacon** [comment]
The TimeWait state is just before closing, and it does not report process information... I should probably cache the information and redisplay when needed.
