### ISSUE TITLE
Add functionality to copy line items

### ISSUE THREAD

**Issue by wesinator** [zodiacon/NetworkExplorer#3]
FYI, it seems copying a selected line item does not work, either from Ctrl+C or Edit menu. 

Since there is no context menu either on netconn line items, does not seem to be a way to copy results 

Would be good to have a context menu with different copy options for copying the entire line item, or individual column items.

Network Explorer v0.1
Windows 10 1909

**Comment by zodiacon** [comment]
Yes, there are a lot of things missing... that's why the version is 0.1 :)
I'm currently working on improving the Sysinternals TcpView, so have less time for my own projects :(

**Comment by zodiacon** [comment]
Added copy and save support
